In [16]:
%reload_ext sql

In [17]:
%sql ibm_db_sa://sdw43109:z-qr1j2pvs81zjz6@dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB

(ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: [IBM][CLI Driver] SQL0438N  Application raised error or warning with diagnostic text: "Exceeded maximum limit of 5 connections. Connection refused".  SQLSTATE=42502 SQLCODE=-438 (Background on this error at: http://sqlalche.me/e/f405)
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['ibm_db_sa://sdw43109:***@dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB'])

In [18]:
%sql select count(*) from CENSUS_DATA;

 * ibm_db_sa://sdw43109:***@dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(Decimal('78'),)]

In [19]:
%sql select count(*) from CHICAGO_PUBLIC_SCHOOLS;

 * ibm_db_sa://sdw43109:***@dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(Decimal('566'),)]

In [30]:
%sql select count(*) from CHICAGO_CRIME_DATA;

 * ibm_db_sa://sdw43109:***@dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(Decimal('533'),)]

In [53]:
%sql SELECT * from CHICAGO_PUBLIC_SCHOOLS LIMIT 2;

 * ibm_db_sa://sdw43109:***@dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(610038, 'Abraham Lincoln Elementary School', 'ES', '615 W Kemper Pl', 'Chicago', 'IL', 60614, '(773) 534-5720', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610038.pdf', 'Fullerton Elementary Network', 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'No', 'Standard', 'Not on Probation', 'Level 1', 'Yes', 'Very Strong', 99, 'Very Strong', '99', 'Strong', 74, 'Strong', 66, 'Strong', '65', 'Strong', '70', 'Strong', '56', 'Average', '47', '96.0%', Decimal('2.0'), '96.4%', '95.8%', '80.1', '43.3', '89.6', '84.9', '60.7', '62.6', '81.9', '85.2', '52', '62.4', '66.3', '77.9', Decimal('69.7'), Decimal('64.4'), Decimal('0.2'), Decimal('0.9'), 'Yellow', 'Green', '67.1', '54.5', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 813, 33, 'NDA', 150000000000000, Decimal('1171699.458'), Decimal('1915829.428'), Decimal('41.92449696'), Decimal('-87.64452163'), 7, 'LINCOLN PARK', 43, 18, '(41.92449696, -87.64452163)'),
 (610281, 'Adam Clayton Powell Paideia Community Academy Elementary School', 'ES', '7511 S South Shore Dr', 'Chicago', 'IL', 60649, '(773) 535-6650', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610281.pdf', 'Skyway Elementary Network', 'SOUTH SIDE COLLABORATIVE', 'No', 'Track_E', 'Not on Probation', 'Level 1', 'No', 'Average', 54, 'Strong', '66', 'Strong', 74, 'Very Strong', 84, 'Strong', '63', 'Strong', '76', 'Weak', '46', 'Average', '50', '95.6%', Decimal('15.7'), '95.3%', '100.0%', '62.4', '51.7', '21.9', '15.1', '29', '42.8', '38.5', '27.4', '44.8', '42.7', '14.1', '34.4', Decimal('16.8'), Decimal('16.5'), Decimal('0.7'), Decimal('1.4'), 'Green', 'Green', '17.2', '27.3', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 521, 46, 'NDA', 150000000000000, Decimal('1196129.985'), Decimal('1856209.466'), Decimal('41.76032435'), Decimal('-87.55673627'), 43, 'SOUTH SHORE', 7, 4, '(41.76032435, -87.55673627)')]

In [72]:
%sql SELECT * from CENSUS_DATA LIMIT 2;

 * ibm_db_sa://sdw43109:***@dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(1, 'Rogers Park', Decimal('7.7'), Decimal('23.6'), Decimal('8.7'), Decimal('18.2'), Decimal('27.5'), 23939, 39),
 (2, 'West Ridge', Decimal('7.8'), Decimal('17.2'), Decimal('8.8'), Decimal('20.8'), Decimal('38.5'), 23040, 46)]

In [74]:
%sql select Communit_Area_Number from CENSUS_DATA;

 * ibm_db_sa://sdw43109:***@dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB
(ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: SQLNumResultCols failed: [IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  "COMMUNIT_AREA_NUMBER" is not valid in the context where it is used.  SQLSTATE=42703 SQLCODE=-206 [SQL: 'select Communit_Area_Number from CENSUS_DATA;'] (Background on this error at: http://sqlalche.me/e/f405)

In [76]:
%sql select TABSCHEMA, TABNAME, CREATE_TIME from syscat.tables where tabschema='SDW43109'

 * ibm_db_sa://sdw43109:***@dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('SDW43109', 'CENSUS_DATA', datetime.datetime(2018, 9, 2, 1, 48, 51, 936370)),
 ('SDW43109', 'CHICAGO_CRIME_DATA', datetime.datetime(2018, 9, 2, 1, 50, 9, 118424)),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', datetime.datetime(2018, 9, 2, 4, 52, 57, 861850)),
 ('SDW43109', 'CHICAGO_SOCIOECONOMIC_DATA', datetime.datetime(2018, 9, 1, 16, 49, 15, 448274)),
 ('SDW43109', 'DEPARTMENTS', datetime.datetime(2018, 9, 1, 10, 54, 48, 396707)),
 ('SDW43109', 'EMPLOYEES', datetime.datetime(2018, 9, 1, 10, 54, 48, 25926)),
 ('SDW43109', 'INSTRUCTOR', datetime.datetime(2018, 9, 1, 16, 11, 3, 765073)),
 ('SDW43109', 'INTERNATIONAL_STUDENT_TEST_SCORES', datetime.datetime(2018, 9, 1, 16, 41, 14, 510102)),
 ('SDW43109', 'JOBS', datetime.datetime(2018, 9, 1, 11, 17, 34, 119633)),
 ('SDW43109', 'JOB_HISTORY', datetime.datetime(2018, 9, 1, 10, 54, 48, 153562)),
 ('SDW43109', 'LOCATIONS', datetime.datetime(2018, 9, 1, 10, 54, 48, 524274))]

In [78]:
%sql select * from syscat.columns where tabname = 'CHICAGO_PUBLIC_SCHOOLS' limit 2;

 * ibm_db_sa://sdw43109:***@dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Rate_of_Misconducts__per_100_students', 33, 'SYSIBM  ', 'DECIMAL', 5, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 288, '+0230.6', '+0000.1', 4, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Average_Teacher_Attendance', 34, 'SYSIBM  ', 'VARCHAR', 5, 0, 'OCTETS', 5, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 55, "'98.1%'", "'91.7%'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None)]

In [142]:
%sql select * from syscat.columns where tabname = 'CENSUS_DATA'

 * ibm_db_sa://sdw43109:***@dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('SDW43109', 'CENSUS_DATA', 'PER_CAPITA_INCOME', 7, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 78, '71551', '10402', 5, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CENSUS_DATA', 'HARDSHIP_INDEX', 8, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 78, '98', '2', 3, None, 0, 20, 10, 1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CENSUS_DATA', 'Community_Area_Number', 0, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 78, '77', '2', 3, None, 0, 20, 10, 1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CENSUS_DATA', 'COMMUNITY_AREA_NAME', 1, 'SYSIBM  ', 'VARCHAR', 22, 0, 'OCTETS', 22, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 78, "'West Town'", "'Archer Heights'", 16, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 11, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CENSUS_DATA', 'PERCENT_OF_HOUSING_CROWDED', 2, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 56, '+015.2', '+000.8', 4, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CENSUS_DATA', 'PERCENT_HOUSEHOLDS_BELOW_POVERTY', 3, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 68, '+051.2', '+003.4', 4, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CENSUS_DATA', 'PERCENT_AGED_16__UNEMPLOYED', 4, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 67, '+034.6', '+004.9', 4, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CENSUS_DATA', 'PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA', 5, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 70, '+051.5', '+002.6', 4, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CENSUS_DATA', 'PERCENT_AGED_UNDER_18_OR_OVER_64', 6, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 67, '+044.9', '+017.0', 4, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None)]

In [79]:
%sql select * from syscat.columns where tabname = 'CHICAGO_CRIME_DATA'

 * ibm_db_sa://sdw43109:***@dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('SDW43109', 'CHICAGO_CRIME_DATA', 'ID', 0, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 533, '11233321', '23469', 5, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_CRIME_DATA', 'Case_Number', 1, 'SYSIBM  ', 'VARCHAR', 8, 0, 'OCTETS', 8, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 533, "'JB155558'", "'G040244'", 13, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 8, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_CRIME_DATA', 'Date', 2, 'SYSIBM  ', 'VARCHAR', 22, 0, 'OCTETS', 22, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 480, "'12/31/2003 10:00:00 PM'", "'01/02/2004 07:09:35 PM'", 27, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 22, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_CRIME_DATA', 'Block', 3, 'SYSIBM  ', 'VARCHAR', 35, 0, 'OCTETS', 35, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 533, "'132XX S RIVERDALE AVE'", "'0000X E OHIO ST'", 23, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 18, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_CRIME_DATA', 'IUCR', 4, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 112, "'5114'", "'0261'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_CRIME_DATA', 'Primary_Type', 5, 'SYSIBM  ', 'VARCHAR', 33, 0, 'OCTETS', 33, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 35, "'THEFT'", "'ASSAULT'", 15, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 10, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_CRIME_DATA', 'Description', 6, 'SYSIBM  ', 'VARCHAR', 46, 0, 'OCTETS', 46, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 103, "'VEHICULAR HIJACKING'", "'AGG CRIM SEX ABUSE FAM MEMBER'", 21, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 16, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_CRIME_DATA', 'Location_Description', 7, 'SYSIBM  ', 'VARCHAR', 33, 0, 'OCTETS', 33, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 48, "'VEHICLE NON-COMMERCIAL'", "'ALLEY'", 16, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 11, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_CRIME_DATA', 'Arrest', 8, 'SYSIBM  ', 'VARCHAR', 5, 0, 'OCTETS', 5, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 2, "'True'", "'False'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_CRIME_DATA', 'Domestic', 9, 'SYSIBM  ', 'VARCHAR', 5, 0, 'OCTETS', 5, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 2, "'True'", "'False'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_CRIME_DATA', 'Beat', 10, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 242, '2534', '112', 3, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_CRIME_DATA', 'District', 11, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 22, '+024.0', '+002.0', 4, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_CRIME_DATA', 'Ward', 12, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 51, '+050.0', '+002.0', 4, None, 0, 20, 10, 43, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_CRIME_DATA', 'Community_Area', 13, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 71, '+077.0', '+002.0', 4, None, 0, 20, 10, 43, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_CRIME_DATA', 'FBI_Code', 14, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 23, "'24'", "'02'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_CRIME_DATA', 'X_Coordinate', 15, 'SYSIBM  ', 'DECIMAL', 9, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 505, '+01204126.0', '+01100955.0', 6, None, 0, 20, 10, 4, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_CRIME_DATA', 'Y_Coordinate', 16, 'SYSIBM  ', 'DECIMAL', 9, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 533, '+01951001.0', '+01817235.0', 6, None, 0, 20, 10, 4, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_CRIME_DATA', 'Year', 17, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 18, '2017', '2002', 3, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_CRIME_DATA', 'Updated_On', 18, 'SYSIBM  ', 'VARCHAR', 22, 0, 'OCTETS', 22, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 10, "'11/22/2016 03:51:04 PM'", "'02/10/2018 03:50:01 PM'", 27, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 22, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_CRIME_DATA', 'Latitude', 19, 'SYSIBM  ', 'DECFLOAT', 16, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 445, '42.021177601', '41.653710536999995', 17, None, 0, 20, 10, 4, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_CRIME_DATA', 'Longitude', 20, 'SYSIBM  ', 'DECIMAL', 30, 14, None, None, None, 'Y', 0, None, None, ' ', ' ', 501, '-0000000000000087.52822297600001', '-0000000000000087.90412275799999', 17, None, 0, 20, 10, 4, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_CRIME_DATA', 'Location', 21, 'SYSIBM  ', 'VARCHAR', 29, 0, 'OCTETS', 29, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 505, "'(42.021177601, -87.67220843)'", "'(41.653710537, -87.609528714)'", 34, None, 0, 20, 10, 4, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 29, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None)]

In [85]:
%sql select * from syscat.columns where tabname = 'CHICAGO_PUBLIC_SCHOOLS'

 * ibm_db_sa://sdw43109:***@dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Rate_of_Misconducts__per_100_students', 33, 'SYSIBM  ', 'DECIMAL', 5, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 288, '+0230.6', '+0000.1', 4, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Average_Teacher_Attendance', 34, 'SYSIBM  ', 'VARCHAR', 5, 0, 'OCTETS', 5, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 55, "'98.1%'", "'91.7%'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Individualized_Education_Program_Compliance_Rate', 35, 'SYSIBM  ', 'VARCHAR', 6, 0, 'OCTETS', 6, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 69, "'99.6%'", "'72.7%'", 11, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 6, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Pk_2_Literacy', 36, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 308, "'96.3'", "'16.4'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Pk_2_Math', 37, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 224, "'97.2'", "'10.1'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Gr3_5_Grade_Level_Math', 38, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 336, "'98.6'", "'10'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Gr3_5_Grade_Level_Read', 39, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 340, "'98.6'", "'10'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Gr3_5_Keep_Pace_Read', 40, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 276, "'82.5'", "'28.8'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Gr3_5_Keep_Pace_Math', 41, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 260, "'83.5'", "'21.7'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Gr6_8_Grade_Level_Math', 42, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 296, "'96.5'", "'10.2'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Gr6_8_Grade_Level_Read', 43, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 300, "'98.9'", "'100'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Gr6_8_Keep_Pace_Math', 44, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 268, "'93.6'", "'24.3'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Gr6_8_Keep_Pace_Read', 45, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 260, "'85.5'", "'21.4'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Gr_8_Explore_Math', 46, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 208, "'9.7'", "'1.4'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Gr_8_Explore_Read', 47, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 244, "'99'", "'1.4'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'ISAT_Exceeding_Math', 48, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 297, '+100.0', '+000.6', 4, None, 0, 20, 10, 90, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'ISAT_Exceeding_Reading', 49, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 261, '+100.0', '+000.5', 4, None, 0, 20, 10, 90, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'ISAT_Value_Add_Math', 50, 'SYSIBM  ', 'DECIMAL', 3, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 57, '+03.6', '-03.1', 3, None, 0, 20, 10, 98, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'ISAT_Value_Add_Read', 51, 'SYSIBM  ', 'DECIMAL', 3, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 60, '+04.9', '-02.8', 3, None, 0, 20, 10, 98, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'ISAT_Value_Add_Color_Math', 52, 'SYSIBM  ', 'VARCHAR', 6, 0, 'OCTETS', 6, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 4, "'Red'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'ISAT_Value_Add_Color_Read', 53, 'SYSIBM  ', 'VARCHAR', 6, 0, 'OCTETS', 6, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 4, "'Red'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Students_Taking__Algebra', 54, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 116, "'98.5'", "'10.5'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Students_Passing__Algebra', 55, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 94, "'93.3'", "'11.1'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', '9th_Grade_ EXPLORE_2009', 56, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 45, "'22.4'", "'11.6'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', '9th_Grade_EXPLORE_2010', 57, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 51, "'22.2'", "'11.2'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', '10th_Grade_PLAN_2009', 58, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 45, "'24.5'", "'12.9'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', '10th_Grade_PLAN_2010_', 59, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 49, "'24.7'", "'12.7'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Net_Change_EXPLORE_and_PLAN', 60, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 16, "'2.3'", "'0.5'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', '11th_Grade_Average_ACT_2011', 61, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 53, "'28.8'", "'13.6'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Net_Change_PLAN_and_ACT', 62, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 30, "'4.3'", "'0.3'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'College_Eligibility', 63, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 78, "'98'", "'10.6'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Graduation_Rate', 64, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 75, "'97.6'", "'10.3'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'College_Enrollment_Rate', 65, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 70, "'90.7'", "'32.6'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'College_Enrollment__number_of_students', 66, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 444, '3320', '26', 3, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'General_Services_Route', 67, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 20, '48', '30', 3, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Freshman_on_Track_Rate', 68, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 79, "'98.1'", "'37.1'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'RCDTS_Code', 69, 'SYSIBM  ', 'BIGINT', 8, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 1, '150000000000000', '150000000000000', 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'X_COORDINATE', 70, 'SYSIBM  ', 'DECIMAL', 13, 3, None, None, None, 'Y', 0, None, None, ' ', ' ', 504, '+0001202756.093', '+0001121355.698', 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Y_COORDINATE', 71, 'SYSIBM  ', 'DECIMAL', 13, 3, None, None, None, 'Y', 0, None, None, ' ', ' ', 560, '+0001949501.716', '+0001817244.896', 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Latitude', 72, 'SYSIBM  ', 'DECIMAL', 18, 8, None, None, None, 'Y', 0, None, None, ' ', ' ', 472, '+0000000042.01709536', '+0000000041.65376037', 11, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Longitude', 73, 'SYSIBM  ', 'DECIMAL', 18, 8, None, None, None, 'Y', 0, None, None, ' ', ' ', 566, '-0000000087.53301251', '-0000000087.82933190', 11, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Community_Area_Number', 74, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 77, '76', '2', 3, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Community_Area_Name', 75, 'SYSIBM  ', 'VARCHAR', 22, 0, 'OCTETS', 22, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 77, "'WEST TOWN'", "'ARCHER HEIGHTS'", 16, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 11, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Ward', 76, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 50, '49', '2', 3, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Police_District', 77, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 23, '24', '2', 3, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Location', 78, 'SYSIBM  ', 'VARCHAR', 27, 0, 'OCTETS', 27, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 536, "'(42.01709536, -87.67779928)'", "'(41.65376037, -87.61434156)'", 32, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 27, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Instruction_Score', 23, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 83, '99', '11', 3, None, 0, 20, 10, 53, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Leaders_Icon', 24, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 6, "'Very Weak'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Leaders_Score', 25, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 79, "'99'", "'14'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Teachers_Icon', 26, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 6, "'Very Weak'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Teachers_Score', 27, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 77, "'99'", "'14'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Parent_Engagement_Icon', 28, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 4, "'Strong'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('SDW43109', 'CHICAGO_PUBLIC_SCHOOLS', 'Parent_Engagement_Score', 29, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 32, "'69'", "'39'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),

In [124]:
%sql SELECT "Community_Area_Name",AVG("College_Enrollment__number_of_students")AS "Average_College_Enrollments"FROM CHICAGO_PUBLIC_SCHOOLS GROUP BY "Community_Area_Name" ;

 * ibm_db_sa://sdw43109:***@dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('ALBANY PARK', Decimal('858.000000')),
 ('ARCHER HEIGHTS', Decimal('2411.500000')),
 ('ARMOUR SQUARE', Decimal('486.000000')),
 ('ASHBURN', Decimal('810.375000')),
 ('AUBURN GRESHAM', Decimal('417.500000')),
 ('AUSTIN', Decimal('475.347826')),
 ('AVALON PARK', Decimal('507.333333')),
 ('AVONDALE', Decimal('910.000000')),
 ('BELMONT CRAGIN', Decimal('1198.833333')),
 ('BEVERLY', Decimal('409.000000')),
 ('BRIDGEPORT', Decimal('633.400000')),
 ('BRIGHTON PARK', Decimal('1205.875000')),
 ('BURNSIDE', Decimal('549.000000')),
 ('CALUMET HEIGHTS', Decimal('261.333333')),
 ('CHATHAM', Decimal('560.222222')),
 ('CHICAGO LAWN', Decimal('1012.285714')),
 ('CLEARING', Decimal('521.250000')),
 ('DOUGLAS', Decimal('424.545454')),
 ('DUNNING', Decimal('761.333333')),
 ('EAST GARFIELD PARK', Decimal('410.538461')),
 ('EAST SIDE', Decimal('1061.000000')),
 ('EDGEWATER', Decimal('766.666666')),
 ('EDISON PARK', Decimal('455.000000')),
 ('ENGLEWOOD', Decimal('401.882352')),
 ('FOREST GLEN', Decimal('477.000000')),
 ('FULLER PARK', Decimal('265.500000')),
 ('GAGE PARK', Decimal('991.500000')),
 ('GARFIELD RIDGE', Decimal('910.400000')),
 ('GRAND BOULEVARD', Decimal('351.125000')),
 ('GREATER GRAND CROSSING', Decimal('405.100000')),
 ('HEGEWISCH', Decimal('481.500000')),
 ('HERMOSA', Decimal('993.750000')),
 ('HUMBOLDT PARK', Decimal('663.076923')),
 ('HYDE PARK', Decimal('482.500000')),
 ('IRVING PARK', Decimal('862.666666')),
 ('JEFFERSON PARK', Decimal('877.500000')),
 ('KENWOOD', Decimal('612.428571')),
 ('LAKE VIEW', Decimal('641.363636')),
 ('LINCOLN PARK', Decimal('802.142857')),
 ('LINCOLN SQUARE', Decimal('826.400000')),
 ('LOGAN SQUARE', Decimal('668.272727')),
 ('LOOP', Decimal('871.000000')),
 ('LOWER WEST SIDE', Decimal('659.727272')),
 ('MCKINLEY PARK', Decimal('388.000000')),
 ('MONTCLARE', Decimal('1317.000000')),
 ('MORGAN PARK', Decimal('654.200000')),
 ('MOUNT GREENWOOD', Decimal('522.750000')),
 ('NEAR NORTH SIDE', Decimal('480.285714')),
 ('NEAR SOUTH SIDE', Decimal('459.333333')),
 ('NEAR WEST SIDE', Decimal('498.437500')),
 ('NEW CITY', Decimal('609.384615')),
 ('NORTH CENTER', Decimal('1077.285714')),
 ('NORTH LAWNDALE', Decimal('321.625000')),
 ('NORTH PARK', Decimal('842.000000')),
 ('NORWOOD PARK', Decimal('808.625000')),
 ('OAKLAND', Decimal('140.000000')),
 ('OHARE', Decimal('786.000000')),
 ('PORTAGE PARK', Decimal('993.428571')),
 ('PULLMAN', Decimal('324.000000')),
 ('RIVERDALE', Decimal('386.750000')),
 ('ROGERS PARK', Decimal('678.000000')),
 ('ROSELAND', Decimal('540.000000')),
 ('SOUTH CHICAGO', Decimal('577.571428')),
 ('SOUTH DEERING', Decimal('464.750000')),
 ('SOUTH LAWNDALE', Decimal('672.409090')),
 ('SOUTH SHORE', Decimal('504.777777')),
 ('UPTOWN', Decimal('626.857142')),
 ('WASHINGTON HEIGHTS', Decimal('445.111111')),
 ('WASHINGTON PARK', Decimal('529.600000')),
 ('WEST ELSDON', Decimal('1233.333333')),
 ('WEST ENGLEWOOD', Decimal('457.384615')),
 ('WEST GARFIELD PARK', Decimal('327.750000')),
 ('WEST LAWN', Decimal('1051.750000')),
 ('WEST PULLMAN', Decimal('324.000000')),
 ('WEST RIDGE', Decimal('910.777777')),
 ('WEST TOWN', Decimal('471.450000')),
 ('WOODLAWN', Decimal('525.750000'))]

In [129]:
%sql SELECT Count(*) FROM CHICAGO_PUBLIC_SCHOOLS WHERE "Healthy_Schools_Certified" LIKE 'Yes'

 * ibm_db_sa://sdw43109:***@dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(Decimal('16'),)]

In [130]:
%sql SELECT Count(*) FROM CHICAGO_CRIME_DATA WHERE "Location_Description" LIKE 'GAS STATION'

 * ibm_db_sa://sdw43109:***@dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(Decimal('6'),)]

In [138]:
%sql SELECT "Community_Area_Name",COUNT("School_ID")AS"No_Of_Schools" FROM CHICAGO_PUBLIC_SCHOOLS GROUP BY "Community_Area_Name" ORDER BY "No_Of_Schools" Desc LIMIT 10;

 * ibm_db_sa://sdw43109:***@dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('AUSTIN', Decimal('23')),
 ('SOUTH LAWNDALE', Decimal('22')),
 ('WEST TOWN', Decimal('20')),
 ('ENGLEWOOD', Decimal('17')),
 ('NEAR WEST SIDE', Decimal('16')),
 ('NORTH LAWNDALE', Decimal('16')),
 ('EAST GARFIELD PARK', Decimal('13')),
 ('ROSELAND', Decimal('13')),
 ('NEW CITY', Decimal('13')),
 ('HUMBOLDT PARK', Decimal('13'))]

In [141]:
%sql SELECT COUNT(*) FROM CHICAGO_CRIME_DATA WHERE "Primary_Type" LIKE 'MOTOR VEHICLE THEFT'

 * ibm_db_sa://sdw43109:***@dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(Decimal('24'),)]

In [147]:
%sql select "CPS.Name_of_School","CPS.Average_Student_Attendance" from CHICAGO_PUBLIC_SCHOOLS as CPS INNER JOIN CENSUS_DATA as CD on CPS.Community_Area_Number=CD.Community_Area_Number where CD.HARDSHIP_INDEX ='96'

 * ibm_db_sa://sdw43109:***@dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB
(ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: SQLNumResultCols failed: [IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  "CPS.COMMUNITY_AREA_NUMBER" is not valid in the context where it is used.  SQLSTATE=42703 SQLCODE=-206 [SQL: 'select "CPS.Name_of_School","CPS.Average_Student_Attendance" from CHICAGO_PUBLIC_SCHOOLS as CPS INNER JOIN CENSUS_DATA as CD on CPS.Community_Area_Number=CD.Community_Area_Number where CD.HARDSHIP_INDEX =\'96\''] (Background on this error at: http://sqlalche.me/e/f405)

In [153]:
%sql select CPS."Name_of_School","Average_Student_Attendance" from CHICAGO_PUBLIC_SCHOOLS AS CPS WHERE "Community_Area_Number" = '30';

 * ibm_db_sa://sdw43109:***@dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('Charles G Hammond Elementary School', '95.3%'),
 ('Cyrus H McCormick Elementary School', '95.9%'),
 ('Daniel J Corkery Elementary School', '94.7%'),
 ('David G Farragut Career Academy High School', '86.1%'),
 ('Eli Whitney Elementary School', '95.8%'),
 ('Emiliano Zapata Elementary Academy', '96.6%'),
 ('Francisco I Madero Middle School', '95.1%'),
 ('Gerald Delgado Kanoon Elementary Magnet School', '95.9%'),
 ('Greater Lawndale High School For Social Justice', '87.5%'),
 ('Ignance Paderewski Elementary Learning Academy', '92.1%'),
 ('Infinity Math Science and Technology High School', '92.2%'),
 ('John Spry Elementary Community School', '96.2%'),
 ('Josefa Ortiz De Dominguez Elementary School', '95.8%'),
 ('Joseph E Gary Elementary School', '96.1%'),
 ('Lazaro Cardenas Elementary School', '96.3%'),
 ('Little Village Elementary School', '96.7%'),
 ('Maria Saucedo Elementary Scholastic Academy', '96.8%'),
 ('Multicultural Academy of Scholarship', '89.2%'),
 ('Rosario Castellanos Elementary School', '96.3%'),
 ('Spry Community Links High School', '95.6%'),
 ('Telpochcalli Elementary School', '95.4%'),
 ('World Language Academy High School', '91.6%')]

In [157]:
%sql select CPS."Name_of_School",CPS."Average_Student_Attendance" 
from CHICAGO_PUBLIC_SCHOOLS as CPS INNER JOIN CENSUS_DATA as CD on CPS."Community_Area_Number"=CD."Community_Area_Number" 
where CD."HARDSHIP_INDEX" ='96'ORDER BY "Average_Student_Attendance" Asc LIMIT 1;

 * ibm_db_sa://sdw43109:***@dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('David G Farragut Career Academy High School', '86.1%')]